[phases.setup]
nixPkgs = ['nodejs-22_x']
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build:prod']

[start]
cmd = 'node server.js'
